Milestone 3: Build React-Redux App
BenMKT/React-Redux-project pull request #1
Opened 2023-09-06 08:14 UTC by BenMKT

# Project implementations: 

- Developed a React application using Redux for state management.
- Created a homepage with a list of items that can be filtered based on user input.
- Integrated an API of choice to retrieve numeric data for the categories.
- Designed and implemented a details page to display detailed data for a selected category.
- Created an About page with more details about the app.
- Implemented navigation between the homepage and details page.
- Ensured code adheres to HTML, CSS, and JavaScript best practices.
- Added appropriate documentation for the project in a professional manner.
- Ensured there are no linter errors in the codebase.
- Followed the correct Gitflow process for version control.

API: 

- Used the Jikan API.
- Selected the Financial Modeling Prep API for obtaining stock data.
- Integrated the API into the application to retrieve numeric values based on parameters.

2023-09-06 09:12 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzFmY2U0ZTkwMmM3ZTM5MDBkNjhhZjk0MjI0OTU3MGNjYjMyMmRhOCZjdD1n/M1fddM48g9084bJMEX/giphy.gif)


# Hi @BenMKT 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- App content has been personalized ✔
- Page navigation works properly ✔
- Correct use of Git Flow ✔
- Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-06 09:12 UTC, AbelG101 commented on src/App.css
> +  list-style: none;
- [x] Kindly make sure to use all the fonts specified in the original design as I noticed you're not using the "gill sans" font please recheck sections of the app that use this font and apply it accordingly.

2023-09-06 09:12 UTC, AbelG101 commented on src/components/Homepage.js
- [ ] As part of the project requirements the Home page should have a list of categories that could be filtered using given parameters (e.g. movie rating, in your case) so please make sure to add this.

2023-09-06 09:12 UTC, AbelG101 commented on src/tests/categoryReducer.test.js
- [ ] Kindly make sure to add unit tests for several components of the app and some pure functions in the Redux code as I noticed you're only testing the category reducer.
- [ ] Also please make sure to add Integration tests to your application you can perform a mocking data fetching and Redux Store connection.

2023-09-06 09:12 UTC, AbelG101 commented on README.md
- [ ] You've done a great job giving an overview of your codebase but you should also explicitly mention a piece of code that you're proud of or find interesting as per the project requirements.

2023-09-06 09:14 UTC, AbelG101 commented
- [ ] Hello @BenMKT please refrain from making changes after you request a review as it will alter the review and cause confusion I noticed you added 2 new commits.

2023-09-06 10:22 UTC, BenMKT commented on src/App.css
> +  list-style: none;
- Changed font family to Gill Sans as per project requirements

2023-09-06 20:36 UTC, BenMKT commented on src/components/Homepage.js
- Added input field to allow the user to filter shows by movie ratings.

2023-09-07 11:47 UTC, BenMKT commented on src/tests/categoryReducer.test.js
- Added tests for `Detailspage` page and `NavBarpage` page.

2023-09-07 12:10 UTC, frank1738 approved these changes
Hi @BenMKT , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/tIeCLkB8geYtW/giphy.gif"/>

## Highlights
✅ Good work adding an additional filter feature👍 

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-07 12:50 UTC, merged